project/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField
from wtforms.validators import DataRequired


class SearchForm (FlaskForm):
    searchterm = StringField(validators=[DataRequired()])

project/__init__.py
# project/__init__.py
import os

from flask import Flask, render_template
from flask_debugtoolbar import DebugToolbarExtension
from flask_bootstrap import Bootstrap


# instantiate the extensions
toolbar = DebugToolbarExtension()
bootstrap = Bootstrap()


def create_app(script_info=None):

    # instantiate the app
    app = Flask(
        __name__,
        template_folder='./templates',
        static_folder='./static'
    )

    # set config
    app_settings = os.getenv(
        'APP_SETTINGS', 'project.config.DevelopmentConfig')
    app.config.from_object(app_settings)

    # set up extensions
    toolbar.init_app(app)
    bootstrap.init_app(app)

    # register blueprints
    from project.main.views import main_blueprint
    app.register_blueprint(main_blueprint)

    # error handlers
    @app.errorhandler(401)
    def unauthorized_page(error):
        return render_template('errors/401.html'), 401

    @app.errorhandler(403)
    def forbidden_page(error):
        return render_template('errors/403.html'), 403

    @app.errorhandler(404)
    def page_not_found(error):
        return render_template('errors/404.html'), 404

    @app.errorhandler(500)
    def server_error_page(error):
        return render_template('errors/500.html'), 500

    # shell context for flask cli
    @app.shell_context_processor
    def ctx():
        return {'app': app}

    return app

project/main/__init__.py
# project/server/main/__init__.py

project/main/views.py
# project/main/views.py


from flask import render_template, Blueprint, redirect, url_for, jsonify
from .forms import SearchForm
#imported requests for accessing the url
import requests
import json

main_blueprint = Blueprint('main', __name__,)


@main_blueprint.route('/', methods=('GET', 'POST'))
def search():
    form = SearchForm()
    if form.validate_on_submit():
        return search_results(form.searchterm.data)
    '''lmt = 3
    tenor_apikey = "Your_key_here"
    responds = requests.get("https://api.tenor.com/v1/autocomplete?key=%s&q=%s&limit=%s" %(tenor_apikey, form.searchterm.data, lmt)).json()
    url =[]
    for item in responds['results']:
        url.append(item)'''
    return render_template('main/index.html', form=form)


@main_blueprint.route("/results")
def search_results(search_query):
    search_results = query_API(search_query)
    return render_template('main/results.html', results=search_results, query=search_query)

def query_API(searchterm):
    # included my API key 
    tenor_apikey = "Your_key_here"
    # get url from tenor-gif website
    url = "https://api.tenor.com/v1/search?q=%s&key=%s" % (searchterm, tenor_apikey)
    # extract information from the url and convert it to json file
    json_query = requests.get(url).json()
    finalurls = []    
    for item in json_query['results']:
        temp = item['media'][0]['tinygif']['url']
        finalurls.append(temp)
    return finalurls

project/templates/_base.html
<!DOCTYPE html>
<html>

  <head>
    <meta charset="utf-8">
    <title>{{ config.APP_NAME }}{% block title %}{% endblock title %}</title>
    <!-- meta -->
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <!-- styles -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="{{url_for('static', filename='main.css')}}" rel="stylesheet" media="screen">
    {% block css %}{% endblock css%}
  </head>

  <body>

    {% include 'header.html' %}

    <div class="site-content">
      <div class="container">

        <!-- messages -->
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
        <br>
        <div class="row">
          <div class="col-md-12">
            {% for category, message in messages %}
            <div class="alert alert-{{ category }}">
              <a class="close" title="Close" href="#" data-dismiss="alert">&times;</a>
              {{message}}
            </div>
            {% endfor %}
          </div>
        </div>
        {% endif %}
        {% endwith %}

        <!-- child template -->
        {% block content %}{% endblock %}

        <br>

        <!-- errors -->
        {% if error %}
          <p class="error"><strong>Error:</strong> {{ error }}</p>
        {% endif %}

      </div>
    </div>

    <br><br>

    {% include 'footer.html' %}

    <!-- scripts -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="{{url_for('static', filename='main.js')}}" type="text/javascript"></script>
    {% block js %}{% endblock %}

  </body>
</html>

project/templates/footer.html
<footer>
  <nav class="navbar fixed-bottom navbar-light bg-light">
    <div class="container">
      <small>
        <span>©
          <a href="/">CodeDoor Coding Challenge</a>
        </span>
      </small>
    </div>
  </nav>
</footer>

project/templates/header.html
<!-- Navigation -->
<nav class="navbar fixed-top navbar-expand-sm navbar-dark bg-dark">
  <div class="container">
    <!-- Navbar Brand -->
    <a class="navbar-brand" href="{{ url_for('main.search') }}">
      <img src="{{url_for('static', filename='icon-white.svg')}}" height="30px">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <!-- Main Navigation -->
      <ul class="navbar-nav">
       
  
      </ul>
    </div>
  </div>
</nav>

project/templates/main/index.html
{% extends "_base.html" %}
<!-- Add the title to the home page-->
{% block title %}
<p>Home Page</p>
{% endblock title %}

<!-- Add the title to the content to the page-->
{% block content %}

<div class = "wrapper">
  <h2>Search GIFs</h2>
  <hr><br>
  <form method="POST" action="/">
    {{ form.csrf_token }}
    {{ form.searchterm(size=20) }}
    <input type="submit" value="Search">
    <!--<div>
      {% for auto in autocomplete %}
      <button>"{{auto}}"</button> 
      {% endfor %}
    </div>-->
</form>
</div>

{% endblock content %}

project/templates/main/results.html
{% extends "_base.html" %}
<!-- Add the title to the result page-->
{% block title %} 
<p>Search Page</p>
{% endblock title %}

<!-- Add the title to the content of the main page-->
{% block content %}
<div class="body-content">a
  <div>
    <h2>Search results for "{{ query }}"</h2>
    <hr><br>
    {%for result in results %}
    <img src="{{result}}" alt="result" width="150" height="150">
    {% endfor %}
  </div>
</div>

{% endblock %}